// Every route the app serves, read off the app directory and written to
// lib/routes.generated.ts for /routes to draw (Brendan, 2026-09-11: "a site
// map showing me every single url"). Run from apps/web:  node scripts/routes/generate.mjs
import fs from "node:fs"
import path from "node:path"

const APP = path.resolve("app")
const routes = []
const walk = (dir, segs) => {
  for (const e of fs.readdirSync(dir, { withFileTypes: true }).sort((a, b) => a.name.localeCompare(b.name))) {
    const p = path.join(dir, e.name)
    if (e.isDirectory()) {
      // A route group is invisible in the URL.
      walk(p, /^\(.*\)$/.test(e.name) ? segs : [...segs, e.name])
    } else if (e.name === "page.tsx") routes.push({ path: "/" + segs.join("/"), kind: "page" })
    else if (e.name === "route.ts") routes.push({ path: "/" + segs.join("/"), kind: "api" })
  }
}
walk(APP, [])
const out = `// Generated by scripts/routes/generate.mjs — do not edit by hand. ${new Date().toISOString().slice(0, 10)}
export type GeneratedRoute = { path: string; kind: "page" | "api" }
export const ROUTES: GeneratedRoute[] = ${JSON.stringify(routes.sort((a, b) => a.path.localeCompare(b.path)), null, 2)}
`
fs.writeFileSync(path.resolve("lib/routes.generated.ts"), out)
console.log(`${routes.length} routes written`)
