// Every route the app serves, read off the app directory and written to
// lib/routes.generated.ts for /routes to draw (Brendan, 2026-09-11: "a site
// map showing me every single url"). Run from apps/web:  node scripts/routes/generate.mjs
import fs from "node:fs"
import path from "node:path"

import { walkRoutes } from "./walk.mjs"

const routes = walkRoutes().map(({ path, kind }) => ({ path, kind }))
const out = `// Generated by scripts/routes/generate.mjs — do not edit by hand. ${new Date().toISOString().slice(0, 10)}
export type GeneratedRoute = { path: string; kind: "page" | "api" }
export const ROUTES: GeneratedRoute[] = ${JSON.stringify(routes, null, 2)}
`
fs.writeFileSync(path.resolve("lib/routes.generated.ts"), out)
console.log(`${routes.length} routes written`)
