// Generated by scripts/routes/generate.mjs — do not edit by hand. 2026-09-11
export type GeneratedRoute = { path: string; kind: "page" | "api" }
export const ROUTES: GeneratedRoute[] = [
  {
    "path": "/",
    "kind": "page"
  },
  {
    "path": "/agent",
    "kind": "page"
  },
  {
    "path": "/agents",
    "kind": "page"
  },
  {
    "path": "/agents/[slug]",
    "kind": "page"
  },
  {
    "path": "/amendments",
    "kind": "page"
  },
  {
    "path": "/amendments/[id]",
    "kind": "page"
  },
  {
    "path": "/api/agents/chat",
    "kind": "api"
  },
  {
    "path": "/api/agents/search",
    "kind": "api"
  },
  {
    "path": "/api/ai/command",
    "kind": "api"
  },
  {
    "path": "/api/ai/copilot",
    "kind": "api"
  },
  {
    "path": "/api/auth/[...nextauth]",
    "kind": "api"
  },
  {
    "path": "/api/connectors/[service]/connect",
    "kind": "api"
  },
  {
    "path": "/api/connectors/callback",
    "kind": "api"
  },
  {
    "path": "/api/connectors/save",
    "kind": "api"
  },
  {
    "path": "/api/connectors/slack/connect",
    "kind": "api"
  },
  {
    "path": "/api/dataset/[state]/[session]/[file]",
    "kind": "api"
  },
  {
    "path": "/api/forms/send",
    "kind": "api"
  },
  {
    "path": "/api/health",
    "kind": "api"
  },
  {
    "path": "/api/laws",
    "kind": "api"
  },
  {
    "path": "/api/map/geocode",
    "kind": "api"
  },
  {
    "path": "/api/markdown/[...path]",
    "kind": "api"
  },
  {
    "path": "/api/news/brief",
    "kind": "api"
  },
  {
    "path": "/api/news/monitor",
    "kind": "api"
  },
  {
    "path": "/api/news/starter",
    "kind": "api"
  },
  {
    "path": "/api/policy/[resource]",
    "kind": "api"
  },
  {
    "path": "/api/policy/commits",
    "kind": "api"
  },
  {
    "path": "/api/policy/forks",
    "kind": "api"
  },
  {
    "path": "/api/policy/forms",
    "kind": "api"
  },
  {
    "path": "/api/policy/forms/[id]",
    "kind": "api"
  },
  {
    "path": "/api/profile",
    "kind": "api"
  },
  {
    "path": "/api/stream",
    "kind": "api"
  },
  {
    "path": "/api/subscribe",
    "kind": "api"
  },
  {
    "path": "/api/traffic",
    "kind": "api"
  },
  {
    "path": "/api/typeset/content",
    "kind": "api"
  },
  {
    "path": "/api/typeset/file/[...key]",
    "kind": "api"
  },
  {
    "path": "/api/typeset/upload",
    "kind": "api"
  },
  {
    "path": "/api/watches",
    "kind": "api"
  },
  {
    "path": "/api/watches/[id]",
    "kind": "api"
  },
  {
    "path": "/api/watches/[id]/test",
    "kind": "api"
  },
  {
    "path": "/api/watches/inbox",
    "kind": "api"
  },
  {
    "path": "/api/watches/inbox/[id]",
    "kind": "api"
  },
  {
    "path": "/api/watches/runs",
    "kind": "api"
  },
  {
    "path": "/auth",
    "kind": "page"
  },
  {
    "path": "/bills",
    "kind": "page"
  },
  {
    "path": "/bills/[id]",
    "kind": "page"
  },
  {
    "path": "/bills/[id]/compare",
    "kind": "page"
  },
  {
    "path": "/briefing",
    "kind": "page"
  },
  {
    "path": "/calendar",
    "kind": "page"
  },
  {
    "path": "/calendar/[view]/[date]",
    "kind": "page"
  },
  {
    "path": "/changelog",
    "kind": "page"
  },
  {
    "path": "/chat",
    "kind": "page"
  },
  {
    "path": "/clips",
    "kind": "page"
  },
  {
    "path": "/committees",
    "kind": "page"
  },
  {
    "path": "/committees/[id]",
    "kind": "page"
  },
  {
    "path": "/connectors",
    "kind": "page"
  },
  {
    "path": "/consensus",
    "kind": "page"
  },
  {
    "path": "/consensus/admin",
    "kind": "page"
  },
  {
    "path": "/consensus/report",
    "kind": "page"
  },
  {
    "path": "/consensus/survey",
    "kind": "page"
  },
  {
    "path": "/create",
    "kind": "page"
  },
  {
    "path": "/departments",
    "kind": "page"
  },
  {
    "path": "/departments/[slug]",
    "kind": "page"
  },
  {
    "path": "/desk",
    "kind": "page"
  },
  {
    "path": "/desk/[state]",
    "kind": "page"
  },
  {
    "path": "/diff",
    "kind": "page"
  },
  {
    "path": "/docs",
    "kind": "page"
  },
  {
    "path": "/docs/api",
    "kind": "page"
  },
  {
    "path": "/docs/api/[state]",
    "kind": "page"
  },
  {
    "path": "/docs/blocks",
    "kind": "page"
  },
  {
    "path": "/docs/blocks/[slug]",
    "kind": "page"
  },
  {
    "path": "/docs/changelog",
    "kind": "page"
  },
  {
    "path": "/docs/changelog-v2",
    "kind": "page"
  },
  {
    "path": "/docs/datasets",
    "kind": "page"
  },
  {
    "path": "/docs/datasets/[state]",
    "kind": "page"
  },
  {
    "path": "/forms",
    "kind": "page"
  },
  {
    "path": "/forms/[id]",
    "kind": "page"
  },
  {
    "path": "/hearings",
    "kind": "page"
  },
  {
    "path": "/hearings/[id]",
    "kind": "page"
  },
  {
    "path": "/home",
    "kind": "page"
  },
  {
    "path": "/laws",
    "kind": "page"
  },
  {
    "path": "/laws/[state]",
    "kind": "page"
  },
  {
    "path": "/legislative-subjects",
    "kind": "page"
  },
  {
    "path": "/legislative-subjects/[state]/[slug]",
    "kind": "page"
  },
  {
    "path": "/lobbying",
    "kind": "page"
  },
  {
    "path": "/lobbying/clients",
    "kind": "page"
  },
  {
    "path": "/lobbying/clients/[name]",
    "kind": "page"
  },
  {
    "path": "/lobbying/firms/[name]",
    "kind": "page"
  },
  {
    "path": "/lobbying/lobbyists",
    "kind": "page"
  },
  {
    "path": "/lobbying/lobbyists/[name]",
    "kind": "page"
  },
  {
    "path": "/map",
    "kind": "page"
  },
  {
    "path": "/meetings/[id]",
    "kind": "page"
  },
  {
    "path": "/members",
    "kind": "page"
  },
  {
    "path": "/members/[id]",
    "kind": "page"
  },
  {
    "path": "/money",
    "kind": "page"
  },
  {
    "path": "/news",
    "kind": "page"
  },
  {
    "path": "/news/[state]",
    "kind": "page"
  },
  {
    "path": "/news/[state]/[id]",
    "kind": "page"
  },
  {
    "path": "/nominations",
    "kind": "page"
  },
  {
    "path": "/nominations/[id]",
    "kind": "page"
  },
  {
    "path": "/policy-areas",
    "kind": "page"
  },
  {
    "path": "/policy-areas/[state]/[slug]",
    "kind": "page"
  },
  {
    "path": "/preview/typeset/[name]",
    "kind": "page"
  },
  {
    "path": "/record",
    "kind": "page"
  },
  {
    "path": "/reports",
    "kind": "page"
  },
  {
    "path": "/roll-call-votes",
    "kind": "page"
  },
  {
    "path": "/roll-call-votes/[session]",
    "kind": "page"
  },
  {
    "path": "/roll-call-votes/[session]/[roll]",
    "kind": "page"
  },
  {
    "path": "/routes",
    "kind": "page"
  },
  {
    "path": "/search",
    "kind": "page"
  },
  {
    "path": "/tags",
    "kind": "page"
  },
  {
    "path": "/typeset",
    "kind": "page"
  },
  {
    "path": "/unite",
    "kind": "page"
  },
  {
    "path": "/unite-2",
    "kind": "page"
  },
  {
    "path": "/watches",
    "kind": "page"
  },
  {
    "path": "/watches/[id]",
    "kind": "page"
  },
  {
    "path": "/watches/inbox",
    "kind": "page"
  },
  {
    "path": "/watches/new",
    "kind": "page"
  },
  {
    "path": "/welcome",
    "kind": "page"
  },
  {
    "path": "/workspace",
    "kind": "page"
  },
  {
    "path": "/workspace/[surface]",
    "kind": "page"
  },
  {
    "path": "/workspace/blocks/[[...slug]]",
    "kind": "page"
  },
  {
    "path": "/workspace/calendar",
    "kind": "page"
  },
  {
    "path": "/workspace/dashboard",
    "kind": "page"
  },
  {
    "path": "/workspace/dashboard/[...page]",
    "kind": "page"
  },
  {
    "path": "/workspace/data",
    "kind": "page"
  },
  {
    "path": "/workspace/data/[...path]",
    "kind": "page"
  },
  {
    "path": "/workspace/typeset",
    "kind": "page"
  },
  {
    "path": "/workspace/typeset-2",
    "kind": "page"
  }
]
