// Generated by scripts/geo/state-districts.mjs — do not edit by hand.
//
// One entry per jurisdiction with district files under /geo, each chamber by
// the name it goes by: a Senate and a House or Assembly, Nebraska's single
// Legislature, the District's Council. `rank` is what the line is coloured
// by, so every state's upper chamber reads the same green and every lower
// the same amber. `count` is what the file holds, for the legend.

export type ChamberRank = "upper" | "lower"

export type StateChamber = {
  /** The overlay's id, and the file's name without its extension. */
  id: string
  chamber: string
  rank: ChamberRank
  file: string
  count: number
}

export type StateDistricts = { code: string; chambers: readonly StateChamber[] }

export const STATE_DISTRICTS = [
  {
    code: "AL",
    chambers: [
      { id: "al-senate", chamber: "Senate", rank: "upper", file: "/geo/al-senate.geojson", count: 35 },
      { id: "al-house", chamber: "House", rank: "lower", file: "/geo/al-house.geojson", count: 105 },
    ],
  },
  {
    code: "AK",
    chambers: [
      { id: "ak-senate", chamber: "Senate", rank: "upper", file: "/geo/ak-senate.geojson", count: 20 },
      { id: "ak-house", chamber: "House", rank: "lower", file: "/geo/ak-house.geojson", count: 40 },
    ],
  },
  {
    code: "AZ",
    chambers: [
      { id: "az-senate", chamber: "Senate", rank: "upper", file: "/geo/az-senate.geojson", count: 30 },
      { id: "az-house", chamber: "House", rank: "lower", file: "/geo/az-house.geojson", count: 30 },
    ],
  },
  {
    code: "AR",
    chambers: [
      { id: "ar-senate", chamber: "Senate", rank: "upper", file: "/geo/ar-senate.geojson", count: 35 },
      { id: "ar-house", chamber: "House", rank: "lower", file: "/geo/ar-house.geojson", count: 100 },
    ],
  },
  {
    code: "CA",
    chambers: [
      { id: "ca-senate", chamber: "Senate", rank: "upper", file: "/geo/ca-senate.geojson", count: 40 },
      { id: "ca-house", chamber: "Assembly", rank: "lower", file: "/geo/ca-house.geojson", count: 80 },
    ],
  },
  {
    code: "CO",
    chambers: [
      { id: "co-senate", chamber: "Senate", rank: "upper", file: "/geo/co-senate.geojson", count: 35 },
      { id: "co-house", chamber: "House", rank: "lower", file: "/geo/co-house.geojson", count: 65 },
    ],
  },
  {
    code: "CT",
    chambers: [
      { id: "ct-senate", chamber: "Senate", rank: "upper", file: "/geo/ct-senate.geojson", count: 37 },
      { id: "ct-house", chamber: "House", rank: "lower", file: "/geo/ct-house.geojson", count: 152 },
    ],
  },
  {
    code: "DE",
    chambers: [
      { id: "de-senate", chamber: "Senate", rank: "upper", file: "/geo/de-senate.geojson", count: 21 },
      { id: "de-house", chamber: "House", rank: "lower", file: "/geo/de-house.geojson", count: 41 },
    ],
  },
  {
    code: "DC",
    chambers: [
      { id: "dc-council", chamber: "Council", rank: "upper", file: "/geo/dc-council.geojson", count: 8 },
    ],
  },
  {
    code: "FL",
    chambers: [
      { id: "fl-senate", chamber: "Senate", rank: "upper", file: "/geo/fl-senate.geojson", count: 40 },
      { id: "fl-house", chamber: "House", rank: "lower", file: "/geo/fl-house.geojson", count: 120 },
    ],
  },
  {
    code: "GA",
    chambers: [
      { id: "ga-senate", chamber: "Senate", rank: "upper", file: "/geo/ga-senate.geojson", count: 56 },
      { id: "ga-house", chamber: "House", rank: "lower", file: "/geo/ga-house.geojson", count: 180 },
    ],
  },
  {
    code: "HI",
    chambers: [
      { id: "hi-senate", chamber: "Senate", rank: "upper", file: "/geo/hi-senate.geojson", count: 25 },
      { id: "hi-house", chamber: "House", rank: "lower", file: "/geo/hi-house.geojson", count: 51 },
    ],
  },
  {
    code: "ID",
    chambers: [
      { id: "id-senate", chamber: "Senate", rank: "upper", file: "/geo/id-senate.geojson", count: 35 },
      { id: "id-house", chamber: "House", rank: "lower", file: "/geo/id-house.geojson", count: 35 },
    ],
  },
  {
    code: "IL",
    chambers: [
      { id: "il-senate", chamber: "Senate", rank: "upper", file: "/geo/il-senate.geojson", count: 60 },
      { id: "il-house", chamber: "House", rank: "lower", file: "/geo/il-house.geojson", count: 119 },
    ],
  },
  {
    code: "IN",
    chambers: [
      { id: "in-senate", chamber: "Senate", rank: "upper", file: "/geo/in-senate.geojson", count: 50 },
      { id: "in-house", chamber: "House", rank: "lower", file: "/geo/in-house.geojson", count: 100 },
    ],
  },
  {
    code: "IA",
    chambers: [
      { id: "ia-senate", chamber: "Senate", rank: "upper", file: "/geo/ia-senate.geojson", count: 50 },
      { id: "ia-house", chamber: "House", rank: "lower", file: "/geo/ia-house.geojson", count: 100 },
    ],
  },
  {
    code: "KS",
    chambers: [
      { id: "ks-senate", chamber: "Senate", rank: "upper", file: "/geo/ks-senate.geojson", count: 40 },
      { id: "ks-house", chamber: "House", rank: "lower", file: "/geo/ks-house.geojson", count: 125 },
    ],
  },
  {
    code: "KY",
    chambers: [
      { id: "ky-senate", chamber: "Senate", rank: "upper", file: "/geo/ky-senate.geojson", count: 38 },
      { id: "ky-house", chamber: "House", rank: "lower", file: "/geo/ky-house.geojson", count: 100 },
    ],
  },
  {
    code: "LA",
    chambers: [
      { id: "la-senate", chamber: "Senate", rank: "upper", file: "/geo/la-senate.geojson", count: 40 },
      { id: "la-house", chamber: "House", rank: "lower", file: "/geo/la-house.geojson", count: 105 },
    ],
  },
  {
    code: "ME",
    chambers: [
      { id: "me-senate", chamber: "Senate", rank: "upper", file: "/geo/me-senate.geojson", count: 35 },
      { id: "me-house", chamber: "House", rank: "lower", file: "/geo/me-house.geojson", count: 151 },
    ],
  },
  {
    code: "MD",
    chambers: [
      { id: "md-senate", chamber: "Senate", rank: "upper", file: "/geo/md-senate.geojson", count: 47 },
      { id: "md-house", chamber: "House", rank: "lower", file: "/geo/md-house.geojson", count: 71 },
    ],
  },
  {
    code: "MA",
    chambers: [
      { id: "ma-senate", chamber: "Senate", rank: "upper", file: "/geo/ma-senate.geojson", count: 40 },
      { id: "ma-house", chamber: "House", rank: "lower", file: "/geo/ma-house.geojson", count: 161 },
    ],
  },
  {
    code: "MI",
    chambers: [
      { id: "mi-senate", chamber: "Senate", rank: "upper", file: "/geo/mi-senate.geojson", count: 38 },
      { id: "mi-house", chamber: "House", rank: "lower", file: "/geo/mi-house.geojson", count: 110 },
    ],
  },
  {
    code: "MN",
    chambers: [
      { id: "mn-senate", chamber: "Senate", rank: "upper", file: "/geo/mn-senate.geojson", count: 67 },
      { id: "mn-house", chamber: "House", rank: "lower", file: "/geo/mn-house.geojson", count: 134 },
    ],
  },
  {
    code: "MS",
    chambers: [
      { id: "ms-senate", chamber: "Senate", rank: "upper", file: "/geo/ms-senate.geojson", count: 52 },
      { id: "ms-house", chamber: "House", rank: "lower", file: "/geo/ms-house.geojson", count: 122 },
    ],
  },
  {
    code: "MO",
    chambers: [
      { id: "mo-senate", chamber: "Senate", rank: "upper", file: "/geo/mo-senate.geojson", count: 34 },
      { id: "mo-house", chamber: "House", rank: "lower", file: "/geo/mo-house.geojson", count: 163 },
    ],
  },
  {
    code: "MT",
    chambers: [
      { id: "mt-senate", chamber: "Senate", rank: "upper", file: "/geo/mt-senate.geojson", count: 50 },
      { id: "mt-house", chamber: "House", rank: "lower", file: "/geo/mt-house.geojson", count: 100 },
    ],
  },
  {
    code: "NE",
    chambers: [
      { id: "ne-legislature", chamber: "Legislature", rank: "upper", file: "/geo/ne-legislature.geojson", count: 49 },
    ],
  },
  {
    code: "NV",
    chambers: [
      { id: "nv-senate", chamber: "Senate", rank: "upper", file: "/geo/nv-senate.geojson", count: 21 },
      { id: "nv-house", chamber: "Assembly", rank: "lower", file: "/geo/nv-house.geojson", count: 42 },
    ],
  },
  {
    code: "NH",
    chambers: [
      { id: "nh-senate", chamber: "Senate", rank: "upper", file: "/geo/nh-senate.geojson", count: 25 },
      { id: "nh-house", chamber: "House", rank: "lower", file: "/geo/nh-house.geojson", count: 165 },
    ],
  },
  {
    code: "NJ",
    chambers: [
      { id: "nj-senate", chamber: "Senate", rank: "upper", file: "/geo/nj-senate.geojson", count: 40 },
      { id: "nj-house", chamber: "Assembly", rank: "lower", file: "/geo/nj-house.geojson", count: 40 },
    ],
  },
  {
    code: "NM",
    chambers: [
      { id: "nm-senate", chamber: "Senate", rank: "upper", file: "/geo/nm-senate.geojson", count: 42 },
      { id: "nm-house", chamber: "House", rank: "lower", file: "/geo/nm-house.geojson", count: 70 },
    ],
  },
  {
    code: "NY",
    chambers: [
      { id: "ny-senate", chamber: "Senate", rank: "upper", file: "/geo/ny-senate.geojson", count: 63 },
      { id: "ny-house", chamber: "Assembly", rank: "lower", file: "/geo/ny-house.geojson", count: 150 },
    ],
  },
  {
    code: "NC",
    chambers: [
      { id: "nc-senate", chamber: "Senate", rank: "upper", file: "/geo/nc-senate.geojson", count: 50 },
      { id: "nc-house", chamber: "House", rank: "lower", file: "/geo/nc-house.geojson", count: 120 },
    ],
  },
  {
    code: "ND",
    chambers: [
      { id: "nd-senate", chamber: "Senate", rank: "upper", file: "/geo/nd-senate.geojson", count: 47 },
      { id: "nd-house", chamber: "House", rank: "lower", file: "/geo/nd-house.geojson", count: 48 },
    ],
  },
  {
    code: "OH",
    chambers: [
      { id: "oh-senate", chamber: "Senate", rank: "upper", file: "/geo/oh-senate.geojson", count: 33 },
      { id: "oh-house", chamber: "House", rank: "lower", file: "/geo/oh-house.geojson", count: 99 },
    ],
  },
  {
    code: "OK",
    chambers: [
      { id: "ok-senate", chamber: "Senate", rank: "upper", file: "/geo/ok-senate.geojson", count: 48 },
      { id: "ok-house", chamber: "House", rank: "lower", file: "/geo/ok-house.geojson", count: 101 },
    ],
  },
  {
    code: "OR",
    chambers: [
      { id: "or-senate", chamber: "Senate", rank: "upper", file: "/geo/or-senate.geojson", count: 30 },
      { id: "or-house", chamber: "House", rank: "lower", file: "/geo/or-house.geojson", count: 60 },
    ],
  },
  {
    code: "PA",
    chambers: [
      { id: "pa-senate", chamber: "Senate", rank: "upper", file: "/geo/pa-senate.geojson", count: 50 },
      { id: "pa-house", chamber: "House", rank: "lower", file: "/geo/pa-house.geojson", count: 203 },
    ],
  },
  {
    code: "PR",
    chambers: [
      { id: "pr-senate", chamber: "Senate", rank: "upper", file: "/geo/pr-senate.geojson", count: 9 },
      { id: "pr-house", chamber: "House", rank: "lower", file: "/geo/pr-house.geojson", count: 41 },
    ],
  },
  {
    code: "RI",
    chambers: [
      { id: "ri-senate", chamber: "Senate", rank: "upper", file: "/geo/ri-senate.geojson", count: 38 },
      { id: "ri-house", chamber: "House", rank: "lower", file: "/geo/ri-house.geojson", count: 75 },
    ],
  },
  {
    code: "SC",
    chambers: [
      { id: "sc-senate", chamber: "Senate", rank: "upper", file: "/geo/sc-senate.geojson", count: 46 },
      { id: "sc-house", chamber: "House", rank: "lower", file: "/geo/sc-house.geojson", count: 124 },
    ],
  },
  {
    code: "SD",
    chambers: [
      { id: "sd-senate", chamber: "Senate", rank: "upper", file: "/geo/sd-senate.geojson", count: 35 },
      { id: "sd-house", chamber: "House", rank: "lower", file: "/geo/sd-house.geojson", count: 37 },
    ],
  },
  {
    code: "TN",
    chambers: [
      { id: "tn-senate", chamber: "Senate", rank: "upper", file: "/geo/tn-senate.geojson", count: 33 },
      { id: "tn-house", chamber: "House", rank: "lower", file: "/geo/tn-house.geojson", count: 99 },
    ],
  },
  {
    code: "TX",
    chambers: [
      { id: "tx-senate", chamber: "Senate", rank: "upper", file: "/geo/tx-senate.geojson", count: 31 },
      { id: "tx-house", chamber: "House", rank: "lower", file: "/geo/tx-house.geojson", count: 150 },
    ],
  },
  {
    code: "UT",
    chambers: [
      { id: "ut-senate", chamber: "Senate", rank: "upper", file: "/geo/ut-senate.geojson", count: 29 },
      { id: "ut-house", chamber: "House", rank: "lower", file: "/geo/ut-house.geojson", count: 75 },
    ],
  },
  {
    code: "VT",
    chambers: [
      { id: "vt-senate", chamber: "Senate", rank: "upper", file: "/geo/vt-senate.geojson", count: 16 },
      { id: "vt-house", chamber: "House", rank: "lower", file: "/geo/vt-house.geojson", count: 109 },
    ],
  },
  {
    code: "VA",
    chambers: [
      { id: "va-senate", chamber: "Senate", rank: "upper", file: "/geo/va-senate.geojson", count: 40 },
      { id: "va-house", chamber: "House", rank: "lower", file: "/geo/va-house.geojson", count: 100 },
    ],
  },
  {
    code: "WA",
    chambers: [
      { id: "wa-senate", chamber: "Senate", rank: "upper", file: "/geo/wa-senate.geojson", count: 49 },
      { id: "wa-house", chamber: "House", rank: "lower", file: "/geo/wa-house.geojson", count: 49 },
    ],
  },
  {
    code: "WV",
    chambers: [
      { id: "wv-senate", chamber: "Senate", rank: "upper", file: "/geo/wv-senate.geojson", count: 17 },
      { id: "wv-house", chamber: "House", rank: "lower", file: "/geo/wv-house.geojson", count: 100 },
    ],
  },
  {
    code: "WI",
    chambers: [
      { id: "wi-senate", chamber: "Senate", rank: "upper", file: "/geo/wi-senate.geojson", count: 34 },
      { id: "wi-house", chamber: "Assembly", rank: "lower", file: "/geo/wi-house.geojson", count: 100 },
    ],
  },
  {
    code: "WY",
    chambers: [
      { id: "wy-senate", chamber: "Senate", rank: "upper", file: "/geo/wy-senate.geojson", count: 31 },
      { id: "wy-house", chamber: "House", rank: "lower", file: "/geo/wy-house.geojson", count: 62 },
    ],
  },
] as const satisfies readonly StateDistricts[]

/** The two colours the legend reads the same way in every state. */
export const RANK_COLOR: Record<ChamberRank, string> = {
  upper: "#059669",
  lower: "#d97706",
}

export type StateOverlayId = (typeof STATE_DISTRICTS)[number]["chambers"][number]["id"]

const BY_ID = new Map<string, { state: StateDistricts; chamber: StateChamber }>(
  STATE_DISTRICTS.flatMap((state) =>
    state.chambers.map((chamber) => [chamber.id, { state, chamber }] as const)
  )
)

export const stateChamber = (id: string) => BY_ID.get(id)
export const chambersOfState = (code: string) =>
  STATE_DISTRICTS.find((s) => s.code === code)?.chambers ?? []
