// What the @44gov registry publishes: one list, read by /docs/components,
// its per-item pages, the rail, and /docs/blocks. registry.json at the repo
// root is what the build reads — keep the two in step: a name here that is
// not there is a command that 404s, and an item there that is not here has
// no page.
//
// 2026-09-12 (Brendan): the list is meant to grow from eleven to thirty and
// beyond, every entry actually portable and actually publishable, with the
// page each one deserves. The "pro" path ships data with a component: an item
// may name a data set, a second registry item that lands rows beside it.

export type RegistryKind = "Component" | "Card" | "Hook" | "Library"

export type RegistryProp = { name: string; type: string; default?: string; description: string }

export type RegistryItem = {
  name: string
  kind: RegistryKind
  /** One sentence, the way a shadcn component page says it. */
  what: string
  /** Title Case, for the page and the index. */
  title: string
  /** Which primitives it stands on: Base UI (the site's), Radix, either, or none. */
  style: "base" | "radix" | "both" | "none"
  /** The named exports, first one first. */
  exports: string[]
  /** Where it lands in a consumer's tree, without the extension. */
  target: string
  /** The JSX (or call) that uses it. */
  usage: string
  props?: RegistryProp[]
  /** Exported functions worth a signature of their own. */
  functions?: { signature: string; description: string }[]
  /** The usage with rows of your own, where the first usage reads the shipped data set. */
  usageOwn?: string
  /** The rows that ship with it, as a second item, when it has any. */
  data?: { item: string; file: string; what: string; rows: string }
}

const T = (target: string) => target.replace(/\.tsx?$/, "")

export const REGISTRY_ITEMS: readonly RegistryItem[] = [
  // ── Libraries ─────────────────────────────────────────────────────────
  {
    name: "district-join",
    kind: "Library",
    title: "District Join",
    what: "Who represents a point, answered by ray-casting the district files: Congress, both state chambers and the county at once.",
    style: "none",
    exports: ["representativesAt", "contains"],
    target: T("lib/map/join.ts"),
    usage: `const who = await representativesAt([-73.75, 42.65])\n// { congress: "NY-20", senate: "NY-44", house: "NY-109", county: "Albany" }`,
  },
  {
    name: "state-districts",
    kind: "Library",
    title: "State Districts",
    what: "Every state legislative chamber with its rank, its boundary file and its district count — 102 chambers, 6,843 districts.",
    style: "none",
    exports: ["STATE_DISTRICTS", "chambersOf"],
    target: T("lib/map/state-districts.ts"),
    usage: `const chambers = chambersOf("TX")\n// [{ chamber: "House", districts: 150, file: ".../tx-house.json" }, …]`,
  },
  {
    name: "state-fips",
    kind: "Library",
    title: "State FIPS",
    what: "The Census's two-digit state codes both ways, and a district number without its padding.",
    style: "none",
    exports: ["fipsOf", "stateOf", "districtNumber"],
    target: T("lib/map/fips.ts"),
    usage: `fipsOf("NY") // "36"\nstateOf("48") // "TX"\ndistrictNumber("NY-020") // 20`,
  },
  {
    name: "map-palette",
    kind: "Library",
    title: "Map Palette",
    what: "A hue per key on the golden angle, the opacities that let washes stack, and the ramps for counts, money, heat and party split.",
    style: "none",
    exports: ["hueFor", "ramp", "WASH"],
    target: T("lib/map/palette.ts"),
    usage: `const color = hueFor("Environmental Conservation")\nconst scale = ramp("money")`,
  },
  {
    name: "map-bounds",
    kind: "Library",
    title: "Map Bounds",
    what: "A bounding box grown over GeoJSON geometry, for flying a map to a feature.",
    style: "none",
    exports: ["boundsOf"],
    target: T("lib/map/bounds.ts"),
    usage: `map.fitBounds(boundsOf(feature), { padding: 40 })`,
  },
  {
    name: "map-basemap",
    kind: "Library",
    title: "Basemap",
    what: "OpenFreeMap's positron style, which needs no key.",
    style: "none",
    exports: ["BASEMAP"],
    target: T("lib/map/basemap.ts"),
    usage: `new maplibregl.Map({ container, style: BASEMAP })`,
  },
  {
    name: "policy-filters",
    kind: "Library",
    title: "Policy Filters",
    what: "The vocabulary the record is read through: state names, party labels, chamber names, and the filter keys every legislative surface speaks.",
    style: "none",
    exports: ["stateName", "partyName", "isJurisdiction", "readFilters", "FILTER_KEYS"],
    target: T("lib/filters.ts"),
    usage: `stateName("NY") // "New York"\npartyName("D") // "Democratic"`,
  },
  {
    name: "policy-imagery",
    kind: "Library",
    title: "Policy Imagery",
    what: "Which picture a jurisdiction, chamber or member gets, which colour a party gets, and the chamber a bill number names.",
    style: "none",
    exports: ["flagUrl", "chamberImage", "hasSeal", "portraitFor", "partyColor", "chamberFromNumber"],
    target: T("lib/imagery.ts"),
    usage: `chamberImage("NY", "Senate") // "https://44gov.nysgpt.com/chambers/ny-senate.avif"\nchamberFromNumber("A11559") // "Assembly"`,
  },
  // ── Hooks ─────────────────────────────────────────────────────────────
  {
    name: "use-local",
    kind: "Hook",
    title: "useLocal",
    what: "State that survives a reload, and reads correctly on the first server-rendered paint.",
    style: "none",
    exports: ["useLocal"],
    target: T("lib/policy/use-local.ts"),
    usage: `const [pinned, setPinned] = useLocal<string[]>("my-app:pinned", [])`,
    props: [
      { name: "key", type: "string", description: "The localStorage key." },
      { name: "initial", type: "T", description: "What the first paint and a fresh browser read." },
    ],
  },
  // ── Components ────────────────────────────────────────────────────────
  {
    name: "seals",
    kind: "Component",
    title: "Seals",
    what: "A jurisdiction's flag chip, a chamber's seal, a member's portrait with its fallback, and a party dot.",
    style: "none",
    exports: ["FlagChip", "ChamberSeal", "MemberPortrait", "PartyDot"],
    target: T("components/policy/seals.tsx"),
    usage: `<ChamberSeal state="NY" chamber="Senate" size={40} />\n<FlagChip state="TX" width={28} />\n<MemberPortrait name="Kirsten Gillibrand" photoUrl={url} state="US" chamber="Senate" size={32} />\n<PartyDot party="D" serving />`,
    props: [
      { name: "state", type: "string", description: "The two-letter jurisdiction; US is Congress." },
      { name: "chamber", type: "string | null", description: "Senate, House or Assembly. Without one, the jurisdiction's own seal." },
      { name: "size", type: "number", default: "40", description: "Width and height in pixels." },
    ],
  },
  {
    name: "directory-search",
    kind: "Component",
    title: "Directory Search",
    what: "The clearable search field a directory is filtered with.",
    style: "base",
    exports: ["SearchDirectory"],
    target: T("components/directory-search.tsx"),
    usage: `const [query, setQuery] = React.useState("")\n<SearchDirectory query={query} setQuery={(v) => setQuery(v ?? "")} placeholder="Search members by name, district or party…" />`,
    props: [
      { name: "query", type: "string", description: "The query." },
      { name: "setQuery", type: "(value: string | null) => void", description: "Called on every keystroke; null on clear." },
      { name: "placeholder", type: "string", description: "What the empty field says." },
    ],
  },
  {
    name: "format",
    kind: "Library",
    title: "Format",
    what: "Dates, numbers, names and bill citations the way the record prints them, and the congress.gov citation table behind them.",
    style: "none",
    exports: ["fmtDate", "fmtNumber", "fmtBill", "fmtCompact", "truncate", "honorific"],
    target: T("lib/format.ts"),
    usage: `fmtBill("HB6644", "US") // "H.R. 6644"\nfmtDate("2026-09-03") // "Sep 3, 2026"\nfmtNumber(18470) // "18,470"`,
  },
  {
    name: "file-block",
    kind: "Component",
    title: "File Block",
    what: "A file with its name on top, line numbers down the side, and Expand when it runs long — the way GitHub shows one.",
    style: "none",
    exports: ["FileBlock"],
    target: T("components/file-block.tsx"),
    usage: `<FileBlock title="hr6644/introduced-in-house.txt" lines={text.split("\\n")} text={() => text} collapsed="data-[state=closed]:max-h-96" />`,
  },
  {
    name: "command-block",
    kind: "Component",
    title: "Command Block",
    what: "shadcn's install-command block: the terminal glyph, package-manager tabs, the copy button and the mono command beneath.",
    style: "none",
    exports: ["CommandBlock", "TerminalGlyph"],
    target: T("components/command-block.tsx"),
    usage: `<CommandBlock tabs={[{ value: "pnpm", label: "pnpm", lines: ["pnpm dlx shadcn@latest add @44gov/seals"] }, { value: "npm", label: "npm", lines: ["npx shadcn@latest add @44gov/seals"] }]} />`,
    props: [
      { name: "tabs", type: "{ value; label; lines: string[] }[]", description: "One tab per package manager; each tab's lines are the command." },
      { name: "icon", type: "ReactNode", default: "<TerminalGlyph />", description: "What sits before the tabs." },
    ],
  },
  {
    name: "copy-button",
    kind: "Component",
    title: "Copy Button",
    what: "The small copy button a code figure wears, with its tick.",
    style: "base",
    exports: ["CopyButton"],
    target: T("components/copy-button.tsx"),
    usage: `<CopyButton value={code} />`,
  },
  {
    name: "code-figure",
    kind: "Component",
    title: "Code Figure",
    what: "A code block with an optional file caption, a copy button, highlighted lines, and a collapsible wrapper for long sources.",
    style: "base",
    exports: ["CodeFigure", "CodeLines"],
    target: T("components/code-block.tsx"),
    usage: `<CodeFigure title="components.json" code={json} collapsible />`,
    props: [
      { name: "code", type: "string", description: "The text, printed as it is." },
      { name: "title", type: "string", description: "A file name above it." },
      { name: "highlighted", type: "Set<number>", description: "Line numbers to mark." },
      { name: "collapsible", type: "boolean", default: "false", description: "Fold a long figure behind Expand." },
    ],
  },
  {
    name: "list-pager",
    kind: "Component",
    title: "List Pager",
    what: "Previous, next and the page numbers under a list, with an ellipsis where the run is long.",
    style: "base",
    exports: ["ListPager", "pageCount", "PAGE_SIZE"],
    target: T("components/list-pager.tsx"),
    usage: `<ListPager page={page} pages={pageCount(rows.length)} onPage={setPage} />`,
  },
  {
    name: "page-header",
    kind: "Component",
    title: "Page Header",
    what: "A page's heading, its one-line description and its actions row, in shadcn's docs measure.",
    style: "none",
    exports: ["PageHeader", "PageHeaderHeading", "PageHeaderDescription", "PageActions"],
    target: T("components/page-header.tsx"),
    usage: `<PageHeader>\n  <PageHeaderHeading>U.S. Congress Bills</PageHeaderHeading>\n  <PageHeaderDescription>The bills most recently acted on.</PageHeaderDescription>\n</PageHeader>`,
  },
  {
    name: "page-actions",
    kind: "Component",
    title: "Page Actions",
    what: "The icon group at the top of a record: open in Typeset, diff the printings, open in Git, copy the page as Markdown, and a menu that opens it in v0, ChatGPT or Claude.",
    style: "base",
    exports: ["DocsCopyPage"],
    target: T("components/docs-copy-page.tsx"),
    usage: `<DocsCopyPage page={markdown} url="https://gov.nysgpt.com/bills/2058568" typeset="/workspace/typeset/bill/2058568" diff="/workspace/typeset/bill/2058568/comp" git="/workspace/typeset/bill/2058568/git" />`,
    props: [
      { name: "page", type: "string", description: "The Markdown the copy button copies." },
      { name: "url", type: "string", description: "The page's public address, for the assistants." },
      { name: "typeset", type: "string", description: "Where it opens in Typeset; omit and the icon is gone." },
      { name: "diff", type: "string", description: "Where its printings open compared." },
      { name: "git", type: "string", description: "Where it opens as a file in Git." },
    ],
  },
  {
    name: "block-shell",
    kind: "Component",
    title: "Block Shell",
    what: "The frame a workspace surface sits in: a collapsible rail, a title bar with actions, the content, and a footer any child can fill.",
    style: "base",
    exports: ["BlockShell", "ShellFooterProvider"],
    target: T("components/policy/block-shell.tsx"),
    usage: `<BlockShell rail={<MyRail />} title={<PathBar crumbs={crumbs} onGo={go} />} actions={<Menu />} footer={<Footer />}>\n  {children}\n</BlockShell>`,
  },
  {
    name: "path-bar",
    kind: "Component",
    title: "Path Bar",
    what: "A breadcrumb that reads as a file path, each crumb a move, with the copy button at the end.",
    style: "base",
    exports: ["PathBar", "APP_CRUMB"],
    target: T("components/create/path-bar.tsx"),
    usage: `<PathBar crumbs={[APP_CRUMB, { label: "Typeset" }, { label: "H.R. 6644" }]} folder={false} onGo={() => {}} />`,
  },
  {
    name: "docs-toc",
    kind: "Component",
    title: "Table of Contents",
    what: "The On This Page rail: the headings of the page, the one in view marked, and a menu of them on a narrow screen.",
    style: "base",
    exports: ["DocsTableOfContents"],
    target: T("components/docs-toc.tsx"),
    usage: `<DocsTableOfContents toc={[{ title: "Installation", url: "#installation", depth: 2 }]} />`,
  },
  {
    name: "typeset-typography",
    kind: "Component",
    title: "Typography",
    what: "H2, H3, Table and Callout as the docs set them, each heading with an anchor that copies its link.",
    style: "none",
    exports: ["H2", "H3", "Table", "Callout", "HeadingAnchor"],
    target: T("components/typeset.tsx"),
    usage: `<H2 id="installation">Installation</H2>\n<Table>…</Table>\n<Callout>Every page says what it is current to.</Callout>`,
  },
  {
    name: "timeline",
    kind: "Component",
    title: "Timeline",
    what: "Rows on a dated rail — a commit list, a bill's actions — each with a title, a meta line and its actions, grouped by day.",
    style: "none",
    exports: ["Timeline", "ago"],
    target: T("components/create/timeline.tsx"),
    usage: `<Timeline rows={[{ key: "1", date: "2026-06-30", title: "Ordered to be Reported (Amended)", meta: "House · step 4" }]} noun="Actions" end="End of the record for this bill" />`,
  },
  {
    name: "record-list",
    kind: "Component",
    title: "Record List",
    what: "A directory row and its list: the seal or an ordinal, the number and status, the meta line, the title, and a skeleton for loading.",
    style: "base",
    exports: ["RecordList", "RecordItem", "RecordSeal", "RecordAvatar", "RecordSkeleton"],
    target: T("components/policy/record-item.tsx"),
    usage: `<RecordList>\n  <RecordItem href="/bills/2058568" avatar={<RecordSeal state="US" chamber="House" />} title="H.R. 6644" lead="Enrolled" meta={["Sep 3, 2026", "Reported", "Mike Flood"]} description="21st Century ROAD to Housing Act" />\n</RecordList>`,
    data: { item: "record-list-data", file: "bills", what: "The bills most recently acted on in Congress,", rows: "25 rows with number, status, sponsor, date and title" },
  },
  {
    name: "paged-list",
    kind: "Component",
    title: "Paged List",
    what: "A record list that pages: previous and next, and a menu for how many rows a page holds.",
    style: "base",
    exports: ["PagedList"],
    target: T("components/policy/paged-list.tsx"),
    usage: `<PagedList items={rows} total={rows.length} pageSize={5} render={(row) => <RecordItem key={row.id} … />} />`,
  },
  {
    name: "data-table",
    kind: "Component",
    title: "Data Table",
    what: "shadcn's data table on TanStack Table 8, with a select column, a filter field, column visibility and the same paging footer the lists use.",
    style: "base",
    exports: ["DataTable", "selectColumn"],
    target: T("components/policy/data-table.tsx"),
    usage: `<DataTable columns={[selectColumn<Row>(), ...columns]} rows={rows} filterColumn="title" filterPlaceholder="Filter titles…" />`,
  },
  {
    name: "preview-frame",
    kind: "Component",
    title: "Preview Frame",
    what: "shadcn's component-preview box, class for class: the rounded frame a component is shown in.",
    style: "none",
    exports: ["PreviewFrame"],
    target: T("components/preview-frame.tsx"),
    usage: `<PreviewFrame>\n  <MyComponent />\n</PreviewFrame>`,
  },
  {
    name: "member-card",
    kind: "Component",
    title: "Member Card",
    what: "A legislator as a row: portrait with its fallback, name, and the line under it.",
    style: "none",
    exports: ["MemberCard", "MemberCardRow"],
    target: T("components/policy/member-card.tsx"),
    usage: `<MemberCard state="US" row={{ id: "G000555", name: "Kirsten Gillibrand", href: "/members/12345", photo: url, chamber: "Senate", line: "Sen. · D–NY", detail: null }} />`,
  },
  {
    name: "project-card",
    kind: "Component",
    title: "Project Card",
    what: "The card the boards are built from: a title, a description, a menu, pin and details, in a grid that wraps — with the Edit details dialog.",
    style: "base",
    exports: ["ProjectCard", "ProjectGrid", "ProjectCardMenu", "ProjectDetails", "useProjectDetails", "EditDetailsDialog"],
    target: T("components/project-card.tsx"),
    usage: `<ProjectGrid>\n  <ProjectCard href="/committees/1" media={<ChamberSeal state="NY" chamber="Assembly" size={28} />} title="Environmental Conservation" meta="NYS Assembly · 412 bills" arrow />\n</ProjectGrid>`,
  },
  {
    name: "card-block",
    kind: "Component",
    title: "Card Block",
    what: "A grid of project cards inside the preview frame, from a list of specs, with Show more when the list runs long.",
    style: "base",
    exports: ["CardBlock"],
    target: T("components/policy/card-block.tsx"),
    usage: `<CardBlock cards={[{ key: "1", href: "/committees/1", title: "Environmental Conservation", meta: "412 bills", media: <ChamberSeal state="NY" chamber="Assembly" size={28} /> }]} initial={6} />`,
  },
  {
    name: "bill-text",
    kind: "Component",
    title: "Bill Text",
    what: "A bill's text set as the legislature prints it — the monospace facsimile — with headings found in the text, blank lines kept, and {+insertions+} and [-strikes-] marked.",
    style: "none",
    exports: ["BillText"],
    target: T("components/bill-text.tsx"),
    usage: `<BillText text={text} version="Introduced in House" date="2026-06-18" />`,
    data: { item: "bill-text-data", file: "bill-text", what: "One printing of a bill,", rows: "the introduced text of H.R. 6644 as the GPO set it" },
  },
  {
    name: "bill-redline",
    kind: "Component",
    title: "Bill Redline",
    what: "Every printing of a bill against the one before it, as one scrolling redline: red strike, then green highlighter at the reading line.",
    style: "none",
    exports: ["BillCompare"],
    target: T("components/bill-compare.tsx"),
    usage: `<BillCompare {...comparison} width="centered" locked />`,
    props: [
      { name: "…comparison", type: "BillComparison", description: "The number, title, printings and passes — the shape /api/policy/bill-compare returns." },
      { name: "width", type: '"centered" | "full"', default: '"centered"', description: "The measure the redline is set to." },
      { name: "locked", type: "boolean", default: "true", description: "A change once shown stays; unlocked, scrolling back replays it." },
    ],
    data: { item: "bill-redline-data", file: "bill-redline", what: "A bill with two printings,", rows: "H.R. 9329's comparison, every pass and row" },
  },
  // ── Cards ─────────────────────────────────────────────────────────────
  {
    name: "card-shell",
    kind: "Component",
    title: "Card Shell",
    what: "The shell a card wears when it stands alone: the Card, a head that takes a title and an action, and the public origin its links fall back to.",
    style: "both",
    exports: ["CardShell", "CardHead", "SITE"],
    target: T("components/cards/card-shell.tsx"),
    usage: `<CardShell>\n  <CardHead title="Votes" action={<Menu />} />\n  …\n</CardShell>`,
  },
  {
    name: "card-foot",
    kind: "Component",
    title: "Card Foot",
    what: "The foot of a card: the chamber pills at the left where there is a chamber to pick, and the circle arrow at the right into the card's own page.",
    style: "both",
    exports: ["CardFoot", "ChamberPills"],
    target: T("components/card-foot.tsx"),
    usage: `<CardFoot chamber={chamber} onChamber={setChamber} state="NY" href="/bills?state=NY" label="All bills" />`,
  },
  {
    name: "votes-card",
    kind: "Card",
    title: "Votes",
    what: "The latest roll calls with their aye/nay split: each row the vote, a two-tone bar sized by the tally, linking to the bill it decided.",
    style: "both",
    exports: ["VotesCard", "VotesCardBody", "Tally"],
    target: T("components/cards/votes-card.tsx"),
    usage: `import rows from "@/lib/44gov/data/votes.json"\n\n<VotesCard rows={rows} state="US" />`,
    props: [
      { name: "rows", type: "VoteRow[]", description: "roll_call_id, bill_id, bill_number, date, chamber, yea, nay." },
      { name: "state", type: "string", default: '"US"', description: "The jurisdiction, for the seals and the pills." },
      { name: "billHref", type: "(row) => string", description: "Where a row goes; the public bill page by default." },
      { name: "limit", type: "number", default: "5", description: "Rows shown after the pills filter." },
    ],
    data: { item: "votes-card-data", file: "votes", what: "The latest roll calls of the current Congress,", rows: "twelve rows with the tally and the bill each decided" },
  },
  {
    name: "committees-card",
    kind: "Card",
    title: "Committees",
    what: "The committees with the most bills before them, each with its seal and count, for either chamber.",
    style: "both",
    exports: ["CommitteesCard", "CommitteesCardBody"],
    target: T("components/cards/committees-card.tsx"),
    usage: `import rows from "@/lib/44gov/data/committees.json"\n\n<CommitteesCard rows={rows} state="US" limit={3} />`,
    data: { item: "committees-card-data", file: "committees", what: "The busiest committees of the current Congress,", rows: "twenty-four rows with chamber and bill count" },
  },
  {
    name: "sessions-card",
    kind: "Card",
    title: "Sessions",
    what: "Every session on file, newest first, each with its bill count; the current one is marked.",
    style: "both",
    exports: ["SessionsCard", "SessionsCardBody"],
    target: T("components/cards/sessions-card.tsx"),
    usage: `import rows from "@/lib/44gov/data/sessions.json"\n\n<SessionsCard rows={rows} current={2025} onPick={(year) => setSession(year)} />`,
    data: { item: "sessions-card-data", file: "sessions", what: "Every Congress on file,", rows: "nine rows with the name, the years and the bill count" },
  },
  {
    name: "topics-card",
    kind: "Card",
    title: "Topics",
    what: "The subjects the session's bills are tagged with, each with its count, as chips.",
    style: "both",
    exports: ["TopicsCard", "TopicsCardBody"],
    target: T("components/cards/topics-card.tsx"),
    usage: `import rows from "@/lib/44gov/data/topics.json"\n\n<TopicsCard rows={rows} limit={8} />`,
    data: { item: "topics-card-data", file: "topics", what: "The most used subject terms of the current Congress,", rows: "twenty-four rows with counts" },
  },
  {
    name: "party-card",
    kind: "Card",
    title: "Party",
    what: "The seats of a chamber by party, as a two-tone bar and a list with counts and shares, for either chamber.",
    style: "both",
    exports: ["PartyCard", "PartyCardBody"],
    target: T("components/cards/party-card.tsx"),
    usage: `import rows from "@/lib/44gov/data/seats.json"\n\n<PartyCard rows={rows} state="US" />`,
    data: { item: "party-card-data", file: "seats", what: "Seats by chamber and party in the current Congress,", rows: "six rows" },
  },
  {
    name: "chambers-card",
    kind: "Card",
    title: "Chambers",
    what: "The chambers of a jurisdiction, each with its seal and who sits in it.",
    style: "both",
    exports: ["ChambersCard", "ChambersCardBody"],
    target: T("components/cards/chambers-card.tsx"),
    usage: `import rows from "@/lib/44gov/data/chambers.json"\n\n<ChambersCard rows={rows} state="US" />`,
    data: { item: "chambers-card-data", file: "chambers", what: "The two chambers of Congress,", rows: "members and bills for each" },
  },
  {
    name: "bills-card",
    kind: "Card",
    title: "Bills",
    what: "Where a session's bills stand, by stage, each a bar against the busiest stage. Any legislature's status names fold into the same stages.",
    style: "both",
    exports: ["BillsCard", "BillsCardBody", "foldStatuses"],
    target: T("components/cards/bills-card.tsx"),
    usage: `import data from "@/lib/44gov/data/bill-stages.json"\n\n<BillsCard statuses={data.statuses} total={data.total} chambers={data.chambers} state="US" />`,
    usageOwn: `<BillsCard\n  state="NY"\n  statuses={[{ value: "In Assembly Committee", count: 4120 }, { value: "Passed Assembly", count: 310 }, { value: "Signed by Governor", count: 96 }]}\n  chambers={{ Assembly: assemblyStatuses, Senate: senateStatuses }}\n/>`,
    props: [
      { name: "statuses", type: "{ value: string; count: number }[]", description: "The jurisdiction's own status names with their counts, for the whole session." },
      { name: "total", type: "number", description: "The session's bill count; the sum of statuses when absent." },
      { name: "chambers", type: "Record<string, { statuses; total? }>", description: "Each chamber's own bills, keyed by chamber. Present, the foot shows the chamber pills and folds the one picked; absent, there are no pills." },
      { name: "state", type: "string", default: '"US"', description: "The jurisdiction. Names the lower chamber (House or Assembly) and the last stage (Became Law under Congress, Signed elsewhere); it does not fetch anything." },
      { name: "stageHref", type: "(row) => string", description: "Where a stage row goes; the public bill list filtered to it by default." },
      { name: "href", type: "string", description: "Where the foot's arrow goes." },
    ],
    functions: [
      {
        signature: `function foldStatuses(statuses: { value: string; count: number }[], state?: string, chamber?: string): { label: string; bills: number; statuses: string[] }[]`,
        description: "Folds a legislature's status names into stages: Introduced, In Committee, Floor Calendar, Engrossed, Crossed Over, Passed, Became Law or Signed, Vetoed, Stricken. A row is where a bill stands now. With a chamber named, the statuses must be that chamber's own bills, and the other chamber's rows fold into Crossed Over.",
      },
    ],
    data: { item: "bills-card-data", file: "bill-stages", what: "The current Congress's statuses,", rows: "every status with its count, for the session and for each chamber's own bills" },
  },
  {
    name: "members-card",
    kind: "Card",
    title: "Members",
    what: "The chamber's members as a grid of portraits with the party dot, faces first and seals where there is no photo.",
    style: "both",
    exports: ["MembersCard", "MembersCardBody"],
    target: T("components/cards/members-card.tsx"),
    usage: `import rows from "@/lib/44gov/data/members.json"\n\n<MembersCard rows={rows} state="US" limit={12} />`,
    data: { item: "members-card-data", file: "members", what: "Sitting members of the current Congress,", rows: "thirty-six rows with portraits, party and chamber" },
  },
  {
    name: "bills-by-party-card",
    kind: "Card",
    title: "Bills by Party",
    what: "Bills introduced by each party's members, month by month, as bars in the flag's red and blue, with the totals and the share beneath.",
    style: "both",
    exports: ["TrafficCard", "TrafficCardBody"],
    target: T("components/cards/traffic-card.tsx"),
    usage: `import rows from "@/lib/44gov/data/bills-by-party.json"\n\n<TrafficCard rows={rows} state="US" />`,
    data: { item: "bills-by-party-card-data", file: "bills-by-party", what: "Six months of bills introduced in Congress,", rows: "one row per month, by party" },
  },
  {
    name: "adopted-card",
    kind: "Card",
    title: "Adopted Bills",
    what: "Bills adopted per session, as an area across the sessions on file.",
    style: "both",
    exports: ["AdoptedCard", "AdoptedCardBody"],
    target: T("components/cards/adopted-card.tsx"),
    usage: `import rows from "@/lib/44gov/data/adopted.json"\n\n<AdoptedCard rows={rows} state="US" />`,
    data: { item: "adopted-card-data", file: "adopted", what: "Bills adopted in every Congress on file,", rows: "nine rows with adopted and total" },
  },
  {
    name: "stats-card",
    kind: "Card",
    title: "Stats",
    what: "A row of number tiles and a ranked list under them: registrations, clients and spend; matched bills and their states.",
    style: "both",
    exports: ["StatsCard", "StatsCardBody"],
    target: T("components/cards/stats-card.tsx"),
    usage: `<StatsCard title="Lobbying" stats={[{ label: "Registrations", value: "12,940" }, { label: "Clients", value: "5,312" }, { label: "Reported spend", value: "$4.4B" }]} list={top.map((name, i) => <div key={name}>{i + 1} {name}</div>)} href="/lobbying" footLabel="Lobbying" />`,
  },
  {
    name: "connect-card",
    kind: "Card",
    title: "Connect",
    what: "An empty state with a row of marks and one call to action: connect a service, invite a team.",
    style: "both",
    exports: ["ConnectCard", "ConnectCardBody"],
    target: T("components/cards/connect-card.tsx"),
    usage: `<ConnectCard marks={[{ name: "Slack", src: "/logos/slack.png" }]} description="Send bills, votes and hearings where your team already works." cta="Connect" href="/connectors" />`,
  },
  {
    name: "api-card",
    kind: "Card",
    title: "API",
    what: "The request that returns the numbers on the page, ready to copy and try.",
    style: "both",
    exports: ["ApiCard", "ApiCardBody"],
    target: T("components/cards/api-card.tsx"),
    usage: `<ApiCard path="/api/policy/bills?state=US&limit=5" />`,
  },
  {
    name: "navigation-card",
    kind: "Card",
    title: "Navigation",
    what: "Groups of links drawn as a sidebar inside a card.",
    style: "both",
    exports: ["NavigationCard", "NavigationCardBody"],
    target: T("components/cards/navigation-card.tsx"),
    usage: `<NavigationCard groups={[{ label: "ArXiv", items: [{ name: "Bills", href: "/bills" }, { name: "Members", href: "/members" }] }]} />`,
  },
  {
    name: "subscribe-card",
    kind: "Card",
    title: "Subscribe",
    what: "What to hear about, and one button that becomes the address field when pressed; Enter sends it.",
    style: "both",
    exports: ["SubscribeCard", "SubscribeCardBody", "DEFAULT_TOPICS"],
    target: T("components/cards/subscribe-card.tsx"),
    usage: `<SubscribeCard endpoint="/api/subscribe" extra={{ list: "weekly" }} />\n// or\n<SubscribeCard onSubscribe={async (email, topics) => save(email, topics)} />`,
  },
  {
    name: "form-chat",
    kind: "Component",
    title: "Form Chat",
    what: "A chat turn that is a form: the ask widget with its fields, repeats, options and gates; the review widget that shows what is known; the progress line. The input field is the form.",
    style: "base",
    exports: ["AskWidget", "ReviewWidget", "FormProgress"],
    target: T("components/chat/ask-widget.tsx"),
    usage: `<AskWidget\n  input={{ section: "household", title: "Your household", fields: [{ key: "applicant.first_name", label: "First name", kind: "text" }] }}\n  form={null}\n  onSubmit={(result) => send(result)}\n/>`,
    props: [
      { name: "input", type: "AskInput", description: "The section, its title and intro, its fields, and a repeat when the section is a list of people." },
      { name: "form", type: "FormId | null", description: "The program the answers belong to; null asks without saving to a form." },
      { name: "answered", type: "AskResult", description: "The receipt already returned, when re-rendering a saved run." },
      { name: "onSubmit", type: "(result: AskResult) => void", description: "What the assistant hears back: answered keys, skipped keys, the next section." },
      { name: "compact", type: "boolean", description: "One column, for a narrow pane." },
    ],
  },
  {
    name: "chat-messages",
    kind: "Component",
    title: "Chat Messages",
    what: "A chat turn that slides in when it arrives and stands still when it is only re-rendered: the reader's turns animate, the assistant's stream in place, with an optional reasoning fold.",
    style: "base",
    exports: ["MessageAnimated", "MESSAGE_ANIMATIONS"],
    target: T("components/chat/message-animated.tsx"),
    usage: `<MessageScroller>\n  {messages.map((m) => (\n    <MessageAnimated key={m.id} message={m} animationPreset={MESSAGE_ANIMATIONS["slide-up"]} />\n  ))}\n</MessageScroller>`,
  },
  {
    name: "code-view",
    kind: "Component",
    title: "Code View",
    what: "A bill's text as a file: line numbers, folding, wrap, search with a match list, a centred measure, and an optional diff against the printing before.",
    style: "none",
    exports: ["CodeView", "collectMatches"],
    target: T("components/policy/code-view.tsx"),
    usage: `<CodeView text={text} wrap fold center query={query} onMatches={(matches) => setMatches(matches)} />`,
    props: [
      { name: "text", type: "string", description: "The printing, as plain text." },
      { name: "original", type: "string | null", description: "The printing before it; with diff on, the view is the change." },
      { name: "diff", type: "boolean", default: "false", description: "Show the change against original." },
      { name: "split", type: "boolean", default: "false", description: "Side by side rather than unified." },
      { name: "query", type: "string", description: "The reader's search; matches come back through onMatches." },
      { name: "highlight", type: "number | null", description: "A zero-based line to light." },
    ],
  },
  {
    name: "code-editor",
    kind: "Component",
    title: "Code Editor",
    what: "The fork editor: the code view made editable, with spaces or tabs, an indent size and wrap.",
    style: "none",
    exports: ["CodeEditor"],
    target: T("components/policy/code-editor.tsx"),
    usage: `<CodeEditor initial={text} onChange={setText} indent="spaces" size={2} wrap={false} />`,
  },
  {
    name: "diff-view",
    kind: "Component",
    title: "Diff View",
    what: "GitHub's diff, unified or split, with hunks that expand, word marks, a search, line permalinks and inline comments.",
    style: "base",
    exports: ["DiffView"],
    target: T("components/policy/diff-view.tsx"),
    usage: `import "@/components/policy/diff-view.css"\n\n<DiffView before={introduced} after={reported} layout="split" reflow onComment={(ref, body) => post(ref, body)} />`,
    props: [
      { name: "before", type: "string", description: "The earlier text." },
      { name: "after", type: "string", description: "The later text." },
      { name: "layout", type: '"unified" | "split"', default: '"unified"', description: "One column or two." },
      { name: "reflow", type: "boolean", default: "false", description: "Diff by words, so a line that only re-wrapped is context." },
      { name: "comments", type: "DiffComment[]", description: "Comments to draw under their lines." },
      { name: "onComment", type: "(ref, body) => void", description: "Absent, the + and the comment items do not appear." },
    ],
  },
]

export const REGISTRY_KINDS: readonly RegistryKind[] = ["Component", "Card", "Hook", "Library"]

export function registryItem(name: string) {
  return REGISTRY_ITEMS.find((i) => i.name === name) ?? null
}

export const REGISTRY_NAMESPACE = "@44gov"
export const REGISTRY_URL = "https://44gov.nysgpt.com/r/{name}.json"

/** The install command, with the data set when asked for. */
export function installLines(name: string, pm: "pnpm" | "npm" | "yarn" | "bun", withData?: string | null) {
  const items = [`${REGISTRY_NAMESPACE}/${name}`, ...(withData ? [`${REGISTRY_NAMESPACE}/${withData}`] : [])].join(" ")
  const runner = pm === "pnpm" ? "pnpm dlx" : pm === "npm" ? "npx" : pm === "yarn" ? "yarn dlx" : "bunx --bun"
  return [`${runner} shadcn@latest add ${items}`]
}
