'use client'

// npm install three @react-three/fiber
//
// Generated by AI Canvas LAB — 60K Particles
// https://aicanvas.me/lab/60k-particles
//
// Drop the matching image into your project's /public folder, or pass a
// different `src` prop. The path below is the default the LAB exporter set.


import { useEffect, useMemo, useRef, useState } from 'react'
import dynamic from 'next/dynamic'
import * as THREE from 'three'
import { Canvas, useFrame, useThree } from '@react-three/fiber'
import type { ThreeEvent } from '@react-three/fiber'

// ── User config (set in LAB) ───────────────────────────────────────────────
const DENSITY               = 45000
const PARTICLE_SIZE         = 4
const COLOR_MODE: 'Original' | 'Mono' = 'Original'
const MONO_COLOR            = '#A8B94D'
const IDLE_AMP              = 0
const IDLE_FREQ             = 0
const HOVER_INFLUENCE_RADIUS = 0.7
const HOVER_DISPLACEMENT    = 1.4
const SPRING_STIFFNESS      = 180
const SPRING_DAMPING        = 18
const HIGHLIGHT_STRENGTH    = 0.25
const LIGHT_MODE            = 3  // 0 TR, 1 TL, 2 Center, 3 None
const Z_JITTER              = 0.05


const PLANE_SIZE = 5.0
const TARGET_LONG_EDGE = 1600
const WORLD_LONG_EDGE = 1.8
const PADDING_PCT = 0.06

// ── Shaders ────────────────────────────────────────────────────────────────
const VERTEX_SHADER = /* glsl */ `
  uniform float uTime;
  uniform vec3  uMouse;
  uniform float uHoverStrength;
  uniform float uInfluenceRadius;
  uniform float uDisplacement;
  uniform float uIdleAmp;
  uniform float uIdleFreq;
  uniform float uBaseSize;
  uniform float uDPR;
  attribute vec3 color;
  varying   vec3 vColor;
  void main() {
    vColor = color;
    vec3 restPos = position;
    float h1 = fract(sin(dot(restPos, vec3(127.1, 311.7,  74.7))) * 43758.5453);
    float h2 = fract(sin(dot(restPos, vec3(269.5, 183.3, 246.1))) * 43758.5453);
    float h3 = fract(sin(dot(restPos, vec3(113.5, 271.9, 124.6))) * 43758.5453);
    vec3 idleOffset = vec3(
      sin(uTime * uIdleFreq * 1.3 + h1 * 6.2831),
      sin(uTime * uIdleFreq * 1.7 + h2 * 6.2831),
      sin(uTime * uIdleFreq * 1.5 + h3 * 6.2831)
    ) * uIdleAmp;
    vec3 toMouse = restPos - uMouse;
    float distXY = length(vec2(toMouse.x, toMouse.y));
    float falloff = 1.0 - smoothstep(0.0, uInfluenceRadius, distXY);
    vec3 raw = vec3(h1, h2, h3) - vec3(0.5);
    vec3 dispersionDir = normalize(raw + vec3(0.0001));
    float magVary = 0.5 + 0.5 * h1;
    vec3 hoverOffset = dispersionDir * (falloff * uHoverStrength * uDisplacement * magVary);
    vec3 worldPos = restPos + idleOffset + hoverOffset;
    vec4 mvPosition = modelViewMatrix * vec4(worldPos, 1.0);
    gl_Position = projectionMatrix * mvPosition;
    gl_PointSize = uBaseSize * uDPR * (1.0 / max(-mvPosition.z, 0.1));
  }
`

const FRAGMENT_SHADER = /* glsl */ `
  precision highp float;
  uniform float uOpacity;
  uniform float uHighlightStrength;
  uniform int   uLightMode;
  varying vec3  vColor;
  void main() {
    vec2 uv = gl_PointCoord;
    vec2 center = uv - vec2(0.5);
    float r = length(center);
    float circle = 1.0 - smoothstep(0.45, 0.5, r);
    if (circle <= 0.001) discard;
    float lit = 0.0;
    if (uLightMode == 0) {
      lit = clamp((uv.x + (1.0 - uv.y)) * 0.5, 0.0, 1.0);
    } else if (uLightMode == 1) {
      lit = clamp(((1.0 - uv.x) + (1.0 - uv.y)) * 0.5, 0.0, 1.0);
    } else if (uLightMode == 2) {
      lit = clamp(1.0 - r * 2.0, 0.0, 1.0);
    } else {
      lit = 0.0;
    }
    lit = pow(lit, 1.6);
    float h = (uLightMode == 3) ? 0.0 : uHighlightStrength;
    vec3 highlight = mix(vColor, vec3(1.0), h);
    vec3 col = mix(vColor, highlight, lit);
    gl_FragColor = vec4(col, circle * uOpacity);
  }
`

// ── Image sampler ──────────────────────────────────────────────────────────
function loadImage(src: string): Promise<HTMLImageElement> {
  return new Promise((resolve, reject) => {
    const img = new Image()
    img.crossOrigin = 'anonymous'
    img.onload = () => resolve(img)
    img.onerror = (e) => reject(e)
    img.src = src
  })
}

async function sample(count: number, src: string) {
  const positions = new Float32Array(count * 3)
  const colors = new Float32Array(count * 3)
  let img: HTMLImageElement
  try { img = await loadImage(src) } catch { return { positions, colors } }
  const iw = img.naturalWidth || img.width || 1
  const ih = img.naturalHeight || img.height || 1
  const aspect = ih / iw
  let cw: number, ch: number
  if (iw >= ih) { cw = TARGET_LONG_EDGE; ch = Math.round(TARGET_LONG_EDGE * aspect) }
  else { ch = TARGET_LONG_EDGE; cw = Math.round(TARGET_LONG_EDGE / aspect) }
  const canvas = document.createElement('canvas')
  canvas.width = cw; canvas.height = ch
  const ctx = canvas.getContext('2d', { willReadFrequently: true })
  if (!ctx) return { positions, colors }
  const drawW = cw * (1 - 2 * PADDING_PCT)
  const drawH = ch * (1 - 2 * PADDING_PCT)
  const fit = Math.min(drawW / cw, drawH / ch)
  const fw = cw * fit, fh = ch * fit
  ctx.drawImage(img, (cw - fw) / 2, (ch - fh) / 2, fw, fh)
  const data = ctx.getImageData(0, 0, cw, ch).data
  const opaque: number[] = []
  for (let i = 0; i < cw * ch; i++) if (data[i * 4 + 3] > 128) opaque.push(i)
  if (opaque.length === 0) return { positions, colors }
  const worldW = cw >= ch ? WORLD_LONG_EDGE : WORLD_LONG_EDGE / aspect
  const worldH = cw >= ch ? WORLD_LONG_EDGE * aspect : WORLD_LONG_EDGE
  const monoRgb = parseHex(MONO_COLOR)
  for (let i = 0; i < count; i++) {
    const pixelIdx = opaque[(Math.random() * opaque.length) | 0]
    const px = pixelIdx % cw
    const py = (pixelIdx / cw) | 0
    positions[i * 3]     = (px / cw - 0.5) * worldW
    positions[i * 3 + 1] = -((py / ch) - 0.5) * worldH
    positions[i * 3 + 2] = (Math.random() - 0.5) * 2 * Z_JITTER
    if (COLOR_MODE === 'Mono') {
      colors[i * 3] = monoRgb[0]; colors[i * 3 + 1] = monoRgb[1]; colors[i * 3 + 2] = monoRgb[2]
    } else {
      const ci = pixelIdx * 4
      colors[i * 3]     = data[ci]     / 255
      colors[i * 3 + 1] = data[ci + 1] / 255
      colors[i * 3 + 2] = data[ci + 2] / 255
    }
  }
  return { positions, colors }
}

function parseHex(hex: string): [number, number, number] {
  const c = hex.replace('#', '').padEnd(6, '0').slice(0, 6)
  return [
    parseInt(c.slice(0, 2), 16) / 255,
    parseInt(c.slice(2, 4), 16) / 255,
    parseInt(c.slice(4, 6), 16) / 255,
  ]
}

// ── Scene ──────────────────────────────────────────────────────────────────
function Field({ src, fit }: { src: string; fit?: number }) {
  const groupRef = useRef<THREE.Group>(null)
  const mouseRef = useRef(new THREE.Vector3(999, 999, 999))
  const hoverActive = useRef(false)
  const hover = useRef(0)
  const hoverVel = useRef(0)
  const { gl, camera, size } = useThree()
  const [data, setData] = useState<{ positions: Float32Array; colors: Float32Array } | null>(null)

  useEffect(() => {
    let alive = true
    sample(DENSITY, src).then((d) => { if (alive) setData(d) })
    return () => { alive = false }
  }, [src])

  // With `fit`, the camera dollies until the sampled image spans that
  // fraction of whichever canvas edge binds first, on every resize — /unite
  // hands the flag a box of any shape. Without it, the LAB's fixed camera.
  useEffect(() => {
    if (!fit || !data || data.positions.length === 0) return
    if (!(camera instanceof THREE.PerspectiveCamera)) return
    let maxX = 0, maxY = 0
    for (let i = 0; i < data.positions.length; i += 3) {
      maxX = Math.max(maxX, Math.abs(data.positions[i]))
      maxY = Math.max(maxY, Math.abs(data.positions[i + 1]))
    }
    const aspect = size.width / Math.max(size.height, 1)
    const halfH = Math.max(maxY, maxX / aspect) / fit
    camera.position.z = halfH / Math.tan(THREE.MathUtils.degToRad(camera.fov / 2))
    camera.updateProjectionMatrix()
  }, [fit, data, camera, size.width, size.height])

  const { geometry, material } = useMemo(() => {
    const geo = new THREE.BufferGeometry()
    if (data && data.positions.length > 0) {
      geo.setAttribute('position', new THREE.BufferAttribute(data.positions, 3))
      geo.setAttribute('color',    new THREE.BufferAttribute(data.colors,    3))
    } else {
      geo.setAttribute('position', new THREE.BufferAttribute(new Float32Array(0), 3))
      geo.setAttribute('color',    new THREE.BufferAttribute(new Float32Array(0), 3))
    }
    const mat = new THREE.ShaderMaterial({
      uniforms: {
        uTime:              { value: 0 },
        uMouse:             { value: new THREE.Vector3(999, 999, 999) },
        uHoverStrength:     { value: 0 },
        uInfluenceRadius:   { value: HOVER_INFLUENCE_RADIUS },
        uDisplacement:      { value: HOVER_DISPLACEMENT },
        uIdleAmp:           { value: IDLE_AMP },
        uIdleFreq:          { value: IDLE_FREQ },
        uBaseSize:          { value: PARTICLE_SIZE },
        uDPR:               { value: gl.getPixelRatio() },
        uOpacity:           { value: 0.95 },
        uHighlightStrength: { value: HIGHLIGHT_STRENGTH },
        uLightMode:         { value: LIGHT_MODE },
      },
      vertexShader: VERTEX_SHADER,
      fragmentShader: FRAGMENT_SHADER,
      transparent: true,
      depthWrite: false,
      blending: THREE.NormalBlending,
    })
    return { geometry: geo, material: mat }
  }, [data, gl])

  useEffect(() => () => { geometry.dispose(); material.dispose() }, [geometry, material])

  function onMove(e: ThreeEvent<PointerEvent>) {
    const local = e.point.clone()
    if (groupRef.current) groupRef.current.worldToLocal(local)
    mouseRef.current.copy(local)
    hoverActive.current = true
  }
  function onLeave() { hoverActive.current = false; mouseRef.current.set(999, 999, 999) }

  useFrame((_, delta) => {
    const dt = Math.min(delta, 1 / 30)
    const u = material.uniforms
    u.uTime.value += dt
    const target = hoverActive.current ? 1 : 0
    const x = hover.current - target
    const a = -SPRING_STIFFNESS * x - SPRING_DAMPING * hoverVel.current
    hoverVel.current += a * dt
    hover.current    += hoverVel.current * dt
    hover.current = Math.max(0, Math.min(1.2, hover.current))
    u.uHoverStrength.value = hover.current
    u.uMouse.value.copy(mouseRef.current)
  })

  return (
    <group ref={groupRef}>
      <points args={[geometry, material]} />
      <mesh
        onPointerMove={onMove}
        onPointerLeave={onLeave}
        onPointerDown={(e) => { (e.target as Element | undefined)?.setPointerCapture?.(e.pointerId); onMove(e) }}
        onPointerUp={(e) => { (e.target as Element | undefined)?.releasePointerCapture?.(e.pointerId); onLeave() }}
      >
        <planeGeometry args={[PLANE_SIZE, PLANE_SIZE]} />
        <meshBasicMaterial transparent opacity={0} depthWrite={false} side={THREE.DoubleSide} />
      </mesh>
    </group>
  )
}

function Scene({ src, fit }: { src: string; fit?: number }) {
  // The LAB shipped this opaque (alpha: false, BG_COLOR as clear colour) so
  // screen recordings stayed sRGB. Here the canvas sits in a themed panel and
  // paints no background of its own — a transparent clear, and the panel's
  // token shows through in both modes (Brendan, 2026-09-09).
  // preserveDrawingBuffer lets WebCodecs / canvas.toBlob read pixels after
  // compositing — without it captures come out black.
  return (
    <Canvas
      dpr={[1, 2]}
      camera={{ position: [0, 0, 4.5], fov: 38 }}
      onCreated={({ camera, gl }) => {
        camera.lookAt(0, 0, 0)
        gl.setClearColor(0x000000, 0)
      }}
      gl={{ antialias: true, alpha: true, preserveDrawingBuffer: true }}
      style={{ touchAction: 'none' }}
    >
      <Field src={src} fit={fit} />
    </Canvas>
  )
}

const SceneNoSSR = dynamic(() => Promise.resolve(Scene), { ssr: false })

/**
 * The LAB's export wrapped itself in a full-screen block with its own centred
 * demo box. Here it fills whatever it is given — the login card's right half —
 * so only that shell changed; the field, the shaders and every constant above
 * are the generated file untouched.
 */
export default function ParticleMark({ src = '/hi-res-am-flag.webp', className, fit }: { src?: string; className?: string; fit?: number } = {}) {
  return (
    <div className={className}>
      <SceneNoSSR src={src} fit={fit} />
    </div>
  )
}
