// One adapter per source shape. States that share a publisher share an
// adapter; a state with a source of its own gets a file of its own. What every
// adapter has in common is the shape it yields, which is the "Laws" table —
// the runner owns the ordering, the tree and the write.
import ak from "./ak.mjs"
import al from "./al.mjs"
import az from "./az.mjs"
import ca from "./ca.mjs"
import co from "./co.mjs"
import ct from "./ct.mjs"
import dc from "./dc.mjs"
import de from "./de.mjs"
import fl from "./fl.mjs"
import hi from "./hi.mjs"
import ia from "./ia.mjs"
import id from "./id.mjs"
import il from "./il.mjs"
import ind from "./in.mjs"
import ks from "./ks.mjs"
import ky from "./ky.mjs"
import la from "./la.mjs"
import ma from "./ma.mjs"
import md from "./md.mjs"
import me from "./me.mjs"
import mi from "./mi.mjs"
import mn from "./mn.mjs"
import mo from "./mo.mjs"
import mt from "./mt.mjs"
import nc from "./nc.mjs"
import nd from "./nd.mjs"
import ne from "./ne.mjs"
import nh from "./nh.mjs"
import nj from "./nj.mjs"
import nm from "./nm.mjs"
import nv from "./nv.mjs"
import ny from "./ny.mjs"
import oh from "./oh.mjs"
import ok from "./ok.mjs"
import or from "./or.mjs"
import pa from "./pa.mjs"
import ri from "./ri.mjs"
import sc from "./sc.mjs"
import sd from "./sd.mjs"
import tx from "./tx.mjs"
import us from "./us.mjs"
import ut from "./ut.mjs"
import va from "./va.mjs"
import vt from "./vt.mjs"
import wi from "./wi.mjs"
import wa from "./wa.mjs"
import wv from "./wv.mjs"
import wy from "./wy.mjs"

export const ADAPTERS = [us, ak, al, az, ca, co, ct, dc, de, fl, hi, ia, id, il, ind, ks, ky, la, ma, md, me, mi, mn, mo, mt, nc, nd, ne, nh, nj, nm, nv, ny, oh, ok, or, pa, ri, sc, sd, tx, ut, va, vt, wa, wi, wv, wy]

export function adapterFor(state) {
  return ADAPTERS.find((a) => a.states.includes(state.toUpperCase())) ?? null
}
