import type { CanonicalKey } from "@/lib/forms/keys"
import type { FormId } from "@/lib/forms/programs"

// A form's spec: what the PDF has, and how the applicant's keys land in it.
//
// Data only. `fields` is generated by scripts/forms/draft-spec.mjs from the
// PDF itself — every field the base carries, with the on-value read from its
// appearance dictionary rather than assumed. `map`, `repeats`, `fixups`,
// `added` and `blank` are authored by sight against the renders that
// scripts/forms/annotate.mjs makes. A spec is complete when every field in
// `fields` is bound, blank, or named in the report; the readback script checks.
//
// One generic fill (lib/forms/fill.ts) walks a spec. There is no per-form
// fill code, which is the point: the 20,000-form library starts from a draft
// spec, not from a blank file.

export type FieldType = "text" | "check" | "radio" | "choice"

export type FieldInfo = {
  name: string
  type: FieldType
  /** 1-based. */
  page: number
  /** PDF points, origin bottom-left: x, y, width, height. */
  rect: [number, number, number, number]
  /** A checkbox or radio kid's export value, from /AP /N. */
  onValue?: string
  /** The printed text beside it, for the reader of this file. */
  label?: string
}

/** How a stored value is written into a text field. */
export type Format =
  | "ssn" // 123-45-6789
  | "ssn-digits"
  | "date" // MM/DD/YYYY
  | "date-mmddyy" // MM-DD-YY
  | "date-mm"
  | "date-dd"
  | "date-yyyy"
  | "money" // 1,234.00
  | "phone" // (555) 555-5555
  | "phone-area"
  | "phone-prefix"
  | "phone-line"
  | "phone-rest" // 555-5555
  | "upper"
  | "label" // the option's printed label
  | "yn" // Y / N
  | "yesno" // Yes / No
  | "initial"

/**
 * One key onto one field.
 *
 * A text binding with neither `when` nor `match` writes the formatted value.
 * With `when` or `match` it writes `mark` (an X) when the value matches — that
 * is how a yes/no answer lands in a form whose yes and no are ruled cells
 * rather than checkboxes. A checkbox binding checks when the value matches
 * and is left unchecked otherwise; several bindings on one box are OR'd.
 */
export type Binding = {
  field: string
  /** Option values that match, `a|b`; `*` is any non-empty value. For a multi key, any chosen value. */
  when?: string
  /** A case-insensitive regular expression the value must match. */
  match?: string
  /** Only when another key holds one of these values (`a|b`). */
  if?: { key: string; is: string }
  format?: Format
  /** What a matched text binding writes. Default X; `=` writes the formatted value itself. */
  mark?: string
}

/** A value built from other keys at fill time, addressed in `map` by its name. */
export type Computed = {
  fn: "join" | "under21" | "jobPeriod" | "nonzero" | "nonempty" | "whoYN" | "notices" | "shelterCost" | "isShelter" | "heatSeparate" | "hasSource" | "age" | "amountPeriod"
  from?: CanonicalKey[]
  sep?: string
  /** For hasSource: the option values that count. */
  arg?: string
}

/**
 * Rows of `[n]` keys onto rows of fields. `{n}` in a template is the row
 * number plus `offset`. With `classify`, rows are grouped by one sub-key's
 * value onto the form's own rows — OCFS-6025 lists income by kind with two
 * earners a kind — and `{class}` and `{slot}` fill in; `{slot:a|b}` picks a
 * name per slot where the form's cells are not named by a formula. A row of
 * a class past `slots` is reported as unmapped, never dropped silently.
 */
export type RepeatBinding = {
  repeat: string
  offset?: number
  rows: number
  classify?: { key: string; classes: Record<string, string>; slots: number }
  /** Sub-key (after `prefix[n].`) → binding template(s). */
  fields: Record<string, Binding | Binding[]>
  /** Per-row bindings where the rows are not a formula: index is the row number minus one. */
  rowFields?: Array<Record<string, Binding | Binding[]>>
  /** Per-class bindings where a class's cells are not the template's; `$present` overrides `present` for the class. */
  classFields?: Record<string, Record<string, Binding | Binding[]>>
  /** Sub-values built from a row's own keys. */
  computed?: Record<string, Computed>
  /** Checked or marked when the row exists at all. */
  present?: Binding | Binding[]
}

/**
 * Fields deliberately left empty: a name, or a region of a page. A base's
 * office-use columns are hundreds of cells; a rule with its reason accounts
 * for them the way a list of names would, and reads.
 */
export type BlankRule = string | { page: number; xMin?: number; xMax?: number; yMin?: number; yMax?: number; type?: FieldType; why: string }

export type Fixup = {
  field: string
  rect?: [number, number, number, number]
  fontSize?: number
  multiline?: boolean
}

export type FormSpec = {
  id: FormId
  code: string
  name: string
  agency: string
  revision: string
  /** /forms/<CODE>.pdf */
  base: string
  fields: FieldInfo[]
  /**
   * Text fields the base lacks, minted at fill time from this geometry and
   * named like the base's. livingston's fillable LDSS-2921 found the ruled
   * grid on most pages and none of the write-in cells on page 2; these are
   * those cells, placed from the printed labels.
   */
  added?: FieldInfo[]
  /** Canonical key (or a computed name) → binding(s). */
  map: Record<string, Binding | Binding[]>
  repeats?: RepeatBinding[]
  computed?: Record<string, Computed>
  fixups?: Fixup[]
  /** Fields deliberately left empty: office use, signatures, questions the vocabulary does not hold. */
  blank: BlankRule[]
}

/** Does a blank rule cover this field? */
export function isBlank(rule: BlankRule, f: FieldInfo): boolean {
  if (typeof rule === "string") return rule === f.name
  if (rule.page !== f.page) return false
  if (rule.type && rule.type !== f.type) return false
  const [x, y] = f.rect
  if (rule.xMin !== undefined && x < rule.xMin) return false
  if (rule.xMax !== undefined && x > rule.xMax) return false
  if (rule.yMin !== undefined && y < rule.yMin) return false
  if (rule.yMax !== undefined && y > rule.yMax) return false
  return true
}

export const asList = <T,>(v: T | T[] | undefined): T[] => (v === undefined ? [] : Array.isArray(v) ? v : [v])
